server:
  port: 18080

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${ALI_YUNBAILIAN_API_KEY}
      model-name: qwen3.7-plus
      log-requests: true
      log-responses: true

logging:
  level:
    dev.langchain4j: debug
